# -*- coding: utf-8 -*-
"""gnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1adjeKBj1nmzNi7IPZwff0id7e1Jlk7Gw
"""

import os
import warnings
import numpy as np
import pandas as pd
import networkx as nx
from sklearn.preprocessing import RobustScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.utils.class_weight import compute_class_weight
from scipy import stats as sp_stats

warnings.simplefilter(action="ignore", category=UserWarning)

DATA_DIR = "/"
OUT_DIR  = "/content/outputs"
CSV_DIR  = os.path.join(OUT_DIR, "csv")
os.makedirs(CSV_DIR, exist_ok=True)
print(f"[INIT] Output directory: {CSV_DIR}\n")

df_feat  = pd.read_csv(os.path.join(DATA_DIR, "elliptic_txs_features.csv"), header=None)
df_feat.columns = ["txId", "time_step"] + [f"f{i}" for i in range(1, 166)]
df_class = pd.read_csv(os.path.join(DATA_DIR, "elliptic_txs_classes.csv"))
df_edges = pd.read_csv(os.path.join(DATA_DIR, "elliptic_txs_edgelist.csv"))

print(f"[LOAD] Features : {df_feat.shape}")
print(f"[LOAD] Classes  : {df_class.shape}")
print(f"[LOAD] Edges    : {df_edges.shape}\n")

# =====================================================================
# DATASET OVERVIEW (Raw Data)
# =====================================================================
print("📊 RAW DATASET OVERVIEW")
print("=" * 40)
print(f"Total Transactions (Nodes) : {len(df_feat):,}")
print(f"Total Edges (Connections)  : {len(df_edges):,}")
print(f"Total Time Steps           : {df_feat['time_step'].nunique()}")

print("\nRaw Class Counts (1=Illicit, 2=Licit, unknown=Unlabeled):")
print(df_class['class'].value_counts())
print("=" * 40)

# Quick check for missing values in the raw state
missing_features = df_feat.isna().sum().sum()
missing_classes = df_class.isna().sum().sum()
print(f"\nMissing values in Features : {missing_features}")
print(f"Missing values in Classes  : {missing_classes}")
print("=" * 40 + "\n")

"""Step 4: Duplicate edge removal"""

before_dupes = len(df_edges)
print(f"Initial edge count: {before_dupes:,}")
print(f"  Duplicate edges found: {df_edges.duplicated().sum():,}")
df_edges = df_edges.drop_duplicates()
print(f"  Duplicate edges removed: {before_dupes - len(df_edges):,}")
print(f"  Final edge count: {len(df_edges):,}")

"""Step 5: Self_Loop Removal"""

before_loops = len(df_edges)
print(f"Initial edge count: {before_loops:,}")
print(f"  Self-loops found: {df_edges.duplicated(subset=['txId1', 'txId2']).sum():,}")
df_edges = df_edges[df_edges["txId1"] != df_edges["txId2"]]
print(f"  Self-loops removed: {before_loops - len(df_edges):,}")
print(f"  Final clean edges count: {len(df_edges):,}")

"""Step 6:Merge features & Labels"""

df = df_feat.merge(df_class, on="txId", how="left")
print(f"Merged DataFrame Shape: {df.shape}")

"""Step 6: Label Encoding"""

label_map = {"1": 1, "2": 0, 1: 1, 2: 0, "unknown": -1}
df["label"] = df["class"].map(label_map)
if df["label"].isna().any():
    raise ValueError(f"Found {df['label'].isna().sum()} unmapped labels. Verify class formats.")
print(df["label"].value_counts())

"""Step 7: Drop Isolated Unknown Nodes"""

all_nodes = set(df["txId"])
connected_nodes = set(df_edges["txId1"]) | set(df_edges["txId2"])
isolated_nodes = all_nodes - connected_nodes
isolated_unknown = df.loc[df["txId"].isin(isolated_nodes) & (df["label"] == -1), "txId"]
df = df[~df["txId"].isin(isolated_unknown)].reset_index(drop=True)
valid_nodes = set(df["txId"])
df_edges = df_edges[
    df_edges["txId1"].isin(valid_nodes) &
    df_edges["txId2"].isin(valid_nodes)
].reset_index(drop=True)
print(f"Total isolated nodes: {len(isolated_nodes):,}")
print(
    f"Isolated labeled nodes kept: "
    f"{len(isolated_nodes) - len(isolated_unknown):,}"
)
print(f"  Isolated unknown nodes dropped: {len(isolated_unknown):,}")
print(f"  Remaining active nodes pool: {len(df):,}")

"""Step 8:Temproal Split Masks & Class Weigth(for imbalance)"""

df["mask"] = df["label"] != -1
train_mask = df["time_step"] <= 34
train_labels = df.loc[(df["label"] != -1) & train_mask, "label"]
weights = compute_class_weight(class_weight="balanced", classes=np.array([0, 1]), y=train_labels)
print(f"Calculated Training Class Weights:")
print(f"  Licit Class (0) Weight:   {weights[0]:.4f}")
print(f"  Illicit Class (1) Weight: {weights[1]:.4f}")

"""Step 9: Skewness /Kurtosis Diagnostic"""

FEATURE_COLS = [f"f{i}" for i in range(1, 166)]
train_feat_df = df.loc[train_mask, FEATURE_COLS]
skew_vals  = train_feat_df.skew()
kurt_vals  = train_feat_df.kurtosis()
diag_df = pd.DataFrame({
    "feature"  : FEATURE_COLS,
    "skewness" : skew_vals.values,
    "kurtosis" : kurt_vals.values,
})
diag_df["high_skew"]     = diag_df["skewness"].abs() > 1
diag_df["high_kurtosis"] = diag_df["kurtosis"].abs() > 3
diag_path = os.path.join(CSV_DIR, "feature_normality_diagnostic.csv")
diag_df.to_csv(diag_path, index=False)
print(f"[DIAG] High-skew features  : {diag_df['high_skew'].sum()}")
print(f"[DIAG] High-kurtosis features : {diag_df['high_kurtosis'].sum()}")
print(f"[DIAG] Saved to -> {diag_path}\n")

"""Step 10: Log1p skew correction"""

high_skew_cols = diag_df.loc[
    diag_df["high_skew"] & (diag_df["skewness"] > 0), "feature"
].tolist()

for col in high_skew_cols:
    # BUG FIX: Calculate shift using training data only to prevent data leakage!
    col_min = df.loc[train_mask, col].min()
    shift   = max(0, -col_min)
    df[col] = np.log1p(df[col] + shift)

print(f"[LOG1P] Applied log1p to {len(high_skew_cols)} positively-skewed features\n")

"""Step 11: Low Variance Removal"""

vt = VarianceThreshold(threshold=0.01)
vt.fit(df.loc[train_mask, FEATURE_COLS])
low_var_mask = vt.get_support()
low_var_cols = [c for c, keep in zip(FEATURE_COLS, low_var_mask) if not keep]
if low_var_cols:
    df.drop(columns=low_var_cols, inplace=True)
    FEATURE_COLS = [c for c in FEATURE_COLS if c not in low_var_cols]
print(f"[VAR1] Low-variance columns removed  : {len(low_var_cols)}")
print(f"[VAR]  Active features after both   : {len(FEATURE_COLS)}\n")

"""Step 12:RobustScaler"""

scaler = RobustScaler()
df.loc[train_mask, FEATURE_COLS] = scaler.fit_transform(
    df.loc[train_mask, FEATURE_COLS]
)
if (~train_mask).any():
    df.loc[~train_mask, FEATURE_COLS] = scaler.transform(
        df.loc[~train_mask, FEATURE_COLS]
    )
print("[SCALE] RobustScaler applied (fit on train, transform all)\n")

"""Step 12: Inf /Nan Handling"""

df[FEATURE_COLS] = df[FEATURE_COLS].replace([np.inf, -np.inf], np.nan)
train_medians    = df.loc[train_mask, FEATURE_COLS].median()
df[FEATURE_COLS] = df[FEATURE_COLS].fillna(train_medians)
print(f"[NAN] Remaining NaN : {df[FEATURE_COLS].isna().sum().sum()}")
print(f"[INF] Remaining Inf : {np.isinf(df[FEATURE_COLS]).sum().sum()}\n")

"""Step 14: High Correlation Feature Removal"""

corr_matrix  = df.loc[train_mask, FEATURE_COLS].corr().abs()
upper_tri    = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)
high_corr_cols = [
    col for col in upper_tri.columns if (upper_tri[col] > 0.95).any()
]
if high_corr_cols:
    df.drop(columns=high_corr_cols, inplace=True)
    FEATURE_COLS = [c for c in FEATURE_COLS if c not in high_corr_cols]
print(f"[CORR] High-correlation columns removed : {len(high_corr_cols)}")
print(f"[CORR] Remaining base features          : {len(FEATURE_COLS)}\n")

pd.DataFrame({"removed_feature": high_corr_cols}).to_csv(
    os.path.join(CSV_DIR, "high_corr_removed.csv"), index=False
)

"""Step 15: Relative Time"""

df["relative_time"] = (df["time_step"] - 1) / 48.0

"""Step 16: Degree feature + Scaling"""

df["in_degree"]  = df["txId"].map(df_edges["txId2"].value_counts()).fillna(0)
df["out_degree"] = df["txId"].map(df_edges["txId1"].value_counts()).fillna(0)
df["degree"]     = df["in_degree"] + df["out_degree"]

degree_scaler = RobustScaler()
df.loc[train_mask, ["degree"]] = degree_scaler.fit_transform(
    df.loc[train_mask, ["degree"]]
)
if (~train_mask).any():
    df.loc[~train_mask, ["degree"]] = degree_scaler.transform(
        df.loc[~train_mask, ["degree"]]
    )

# Form final feature index list
FINAL_FEATURES = FEATURE_COLS + ["relative_time", "degree"]
print("Degree scaled. Final features:")
print(FINAL_FEATURES)

"""Step 17:"""

df["split_group"] = "test"  # Default fallback for t >= 40
df.loc[df["time_step"] <= 34, "split_group"] = "train"
df.loc[(df["time_step"] >= 35) & (df["time_step"] <= 39), "split_group"] = "val"

print("Node volume distribution per split:")
print(df["split_group"].value_counts())

NODE_OUTPUT_COLS = ["txId", "time_step", "split_group", "label", "mask"] + FINAL_FEATURES

nodes_path = os.path.join(CSV_DIR, "preprocessed_nodes.csv")
edges_path = os.path.join(CSV_DIR, "preprocessed_edges.csv")

# Generate CSV representations
df[NODE_OUTPUT_COLS].to_csv(nodes_path, index=False)
df_edges.to_csv(edges_path, index=False)

print(f"Saved master node data to -> {nodes_path} ({len(df):,} rows)")
print(f"Saved master edge data to -> {edges_path} ({len(df_edges):,} rows)")

# 1. Save ordered column array
pd.DataFrame({"feature_name": FINAL_FEATURES}).to_csv(
    os.path.join(CSV_DIR, "feature_names.csv"), index=False
)

# 2. Save calculated class balance constants
pd.DataFrame({
    "class_id": [0, 1],
    "class_name": ["licit", "illicit"],
    "balanced_weight": weights
}).to_csv(os.path.join(CSV_DIR, "class_weights.csv"), index=False)

# 3. Save snapshot specifications and diagnostic values
time_steps = sorted(df["time_step"].unique())
metadata_df = pd.DataFrame([{
    "num_features": len(FINAL_FEATURES),
    "num_classes": 2,
    "num_snapshots": len(time_steps),
    "train_range_start": 1, "train_range_end": 34,
    "val_range_start": 35, "val_range_end": 39,
    "test_range_start": 40, "test_range_end": 49,
    "num_licit": int((df["label"] == 0).sum()),
    "num_illicit": int((df["label"] == 1).sum()),
    "num_unknown": int((df["label"] == -1).sum())
}])
metadata_df.to_csv(os.path.join(CSV_DIR, "metadata.csv"), index=False)


print("PROCESSING SCRIPT COMPLETE")

print(f"All files saved in directory: {CSV_DIR}")
print(os.listdir(CSV_DIR))

import matplotlib.pyplot as plt
import seaborn as sns

# Set a clean, professional style for the plots
sns.set_theme(style="whitegrid", font_scale=1.1)

# Create a readable string label for the plots based on your numeric mapping
# -1: Unknown, 0: Licit, 1: Illicit
label_names = {-1: 'Unknown', 0: 'Licit', 1: 'Illicit'}
df['class_name'] = df['label'].map(label_names)

# =====================================================================
# 1. Dataset Overview (Text Summary)
# =====================================================================
print("📊 DATASET OVERVIEW")
print("=" * 30)
print(f"Total Transactions (Nodes) : {len(df):,}")
print(f"Total Edges (Connections)  : {len(df_edges):,}")
print(f"Total Time Steps           : {df['time_step'].nunique()}")
print("\nClass Counts:")
print(df['class_name'].value_counts())
print("=" * 30)

# =====================================================================
# 2. Class Distribution (Bar Plot & Pie Chart side-by-side)
# =====================================================================


# Bar Plot
sns.countplot(
    data=df,
    x='class_name',
    order=['Unknown', 'Licit', 'Illicit'],
    palette=['#95a5a6', '#2ecc71', '#e74c3c'],
    ax=axes[0]
)
axes[0].set_title("Class Distribution (Bar Plot)", fontweight='bold')
axes[0].set_ylabel("Number of Transactions")
axes[0].set_xlabel("")

plt.show()